matrix:
  include:
    -language:c
     sudo:false #onlyforfasterbuilds
     compiler:
        -clang
        -gcc
      script:
         -gcc -o test test.c  //wecanusegccinsteadofclangtoo
         -./test
